"""empty message

Revision ID: ce82026bb761
Revises: 
Create Date: 2019-03-10 00:48:12.794841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce82026bb761'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('powers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('avengers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('power_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['power_id'], ['powers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avengers_email'), 'avengers', ['email'], unique=True)
    op.create_index(op.f('ix_avengers_first_name'), 'avengers', ['first_name'], unique=False)
    op.create_index(op.f('ix_avengers_last_name'), 'avengers', ['last_name'], unique=False)
    op.create_index(op.f('ix_avengers_username'), 'avengers', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_avengers_username'), table_name='avengers')
    op.drop_index(op.f('ix_avengers_last_name'), table_name='avengers')
    op.drop_index(op.f('ix_avengers_first_name'), table_name='avengers')
    op.drop_index(op.f('ix_avengers_email'), table_name='avengers')
    op.drop_table('avengers')
    op.drop_table('powers')
    op.drop_table('departments')
    # ### end Alembic commands ###
